[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "使用仓颉语言制作的bacnet编解码库"
  link-option = ""
  name = "BACnetCodec4cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.1.0"
  package-configuration = {}
